name    'larstobi-pe_r10k'
version '0.0.1'
source 'http://github.com/larstobi/puppet-pe_r10k.git'
author 'larstobi'
license 'Apache License, Version 2.0'
summary 'Puppet module to install r10k for a Puppet Enterprise puppet master.'
description 'This puppet module will install r10k and a Rack app that runs r10k on a HTTP POST with a payload.'
project_page 'http://github.com/larstobi/puppet-pe_r10k.git'
dependency 'puppetlabs/pe_gem'
